#!/bin/bash -x

# This script should be ran via /boot/firmware/cmdline.txt (or /boot/cmdline.txt if no firmware directory) by adding " quiet init=/usr/sbin/reconfig-clusterctrl X"
# where X is replaced by either cbridge, cnat, p1, p2, p3, p4 depending on which image you want to setup.
# 
# Once added reboot the Pi and on first boot the script will reconfigure the Pi and then reboot again
#

reboot_pi () {
  umount /boot
  umount /boot/firmware
  sync
  echo b > /proc/sysrq-trigger
  sleep 5
  exit 0
}

if [ -z $1 ];then
  # Unknown argument passed - do nothing
  echo "No reconfig"
  exit 0
fi

mount -t proc proc /proc
mount -t sysfs sys /sys

# Configure for ClusterCTRL
# Parameter can be either p1 to p252 for nodes and cbridge or cnat for controller
#

CONFIGDIR="/usr/share/clusterctrl"

if [ -d /boot/firmware ];then
  BOOT="/boot/firmware"
else
  BOOT="/boot"
fi
# mount $BOOT

if [ -f /etc/os-release ]; then
  source /etc/os-release
fi

mount -o remount,rw /

NUMBER='^[0-9]+$'
if [ ${#1} -gt 1 ] && [ ${1:0:1} = "p" ] && [[ ${1:1} =~ $NUMBER  ]] && [ ${1:1} -gt 0 ] && [ ${1:1} -lt 253 ]; then

  # Backup kernel cmdline.txt file
  INIT_CONF=$BOOT/armbianEnv.txt
  rm -f $INIT_CONF.old
  cp -s $INIT_CONF $INIT_CONF.old

  # Remove config file entries and add them back in later if needed
  # sed -i "s# console=ttyGS0##" $INIT_CONF  
  sed -i 's/^\(extraargs=.*\)init=\/usr\/sbin\/reconfig-clusterctrl cbridge\(.*\)/\1\2/' $INIT_CONF
  sed -i 's/^\(extraargs=.*\)init=\/usr\/sbin\/reconfig-clusterctrl cnat\(.*\)/\1\2/' $INIT_CONF
  sed -i 's/^\(extraargs=.*\)init=\/usr\/sbin\/reconfig-clusterctrl p[0-9]\(.*\)/\1\2/' $INIT_CONF
  sed -i 's/^\(extraargs=.*\)init=\/sbin\/reconfig-clusterctrl cbridge\(.*\)/\1\2/' $INIT_CONF
  sed -i 's/^\(extraargs=.*\)init=\/sbin\/reconfig-clusterctrl cnat\(.*\)/\1\2/' $INIT_CONF
  sed -i 's/^\(extraargs=.*\)init=\/sbin\/reconfig-clusterctrl p[0-9]\(.*\)/\1\2/' $INIT_CONF

  if [ -f /etc/dhcpcd.conf ]; then
    # sed -i "s/^\(denyinterfaces.*\) eth0\(.*\)/\1\2/" /etc/dhcpcd.conf
    rm /etc/dhcpcd.conf
  fi
  if [ -f /etc/dhcp/dhclient.conf ]; then
    rm /etc/dhcp/dhclient.conf
  fi

  if [ -f /etc/default/clusterctrl ];then
    sed -i '/TYPE=.*/d' /etc/default/clusterctrl
    sed -i '/ID=.*/d' /etc/default/clusterctrl
    RESIZE=0
  else
    # Only run resize/firstboot on the first boot
    RESIZE=1
    cp -f "$CONFIGDIR/default-clusterctrl" /etc/default/clusterctrl
  fi

  # Setup the interfaces/issue files
  P=${1:1}
  rm -f /etc/network/interfaces.d/clusterctrl
  rm -f /etc/systemd/network/*
  
  echo "$1" > /etc/hostname
  
  cat >/etc/systemd/network/10-usb0.link << END
[Match]
OriginalName=usb0
Driver=g_ether

[Link]
MACAddress=00:22:82:ff:ff:0$P
END

  # Defaults to brigged controller. If $BOOT/cnat exists then assume natted controller
  if [ -f $BOOT/cnat ]; then
    cat >/etc/systemd/network/10-usb0.network << END
[Match]
Name=usb0
MACAddress=00:22:82:ff:ff:0$P

[Link]
RequiredForOnline=no

[Network]
Description=Interface usb0 for P$P
DHCP=no

[Address]
Address=172.19.181.$P/24
Gateway=172.19.181.254
Label=usb0:1

[Route]
Destination=0.0.0.0/0
Gateway=172.19.181.254
END
  else
  cat >/etc/systemd/network/10-usb0.network << END
[Match]
Name=usb0
MACAddress=00:22:82:ff:ff:0$P

[Link]
RequiredForOnline=no

[Network]
Description=Interface usb0 for P$P
DHCP=yes

[DHCP]
RouteMetric=100

[Address]
Address=172.19.181.$P/24
Gateway=172.19.181.254
Label=usb0:1
END
  fi

  ln -fs /lib/systemd/system/getty@.service \
    /etc/systemd/system/getty.target.wants/getty@ttyGS0.service
  systemctl disable clusterctrl-init
  sed -i "s/^net.ipv4.ip_forward=1 # ClusterCTRL/#net.ipv4.ip_forward=1 # ClusterCTRL/" /etc/sysctl.conf
  echo "TYPE=node" >> /etc/default/clusterctrl
  echo "ID=$P" >> /etc/default/clusterctrl
  systemctl enable clusterctrl-composite
fi

mount -o remount,ro /

# if [ $RESIZE -eq 1 ];then
#  if [ -f /usr/lib/raspberrypi-sys-mods/firstboot ];then
#   sed -i 's#$# init=/usr/lib/raspberrypi-sys-mods/firstboot#' $INIT_CONF
#  elif [ -f /usr/lib/raspi-config/init_resize.sh ] && [ ! -f /$BOOT/noresize ] && [ ! -f /$BOOT/noresize.txt ];then
#   sed -i 's#$# init=/usr/lib/raspi-config/init_resize.sh#' $INIT_CONF
#  fi
# fi

sync

# Reboot the Pi
reboot_pi
